- name: Install mitmproxy dependencies
  apt:
    pkg:
      - build-essential
      - libssl-dev
      - liblz4-dev
      - libffi-dev
      - libxslt-dev
      - python3-dev
      - libxslt-dev

- name: Install mitmproxy
  pip:
    name: mitmproxy
    executable: pip3
    state: latest

- name: create mitmproxy system user
  user:
    name: mitmproxy
    system: true
    shell: /usr/sbin/nologin
    home: /var/lib/mitmproxy
    createhome: true

- name: enable ipv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
  when: mitmproxy_allow_ipv4_forwarding is defined

- name: create systemd service unit
  template:
    src: mitmweb.service.j2
    dest: /etc/systemd/system/mitmweb.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart mitmweb

- name: configure mitmweb
  template:
    src: mitmweb.j2
    dest: /etc/default/mitmweb
    owner: root
    group: root
    mode: 0644
  notify:
    - restart mitmweb
